//! Architecture check on the rustc engine: judges the primary config's
//! resolved reference graph ([`SemanticModel::references_from`]) instead of
//! the retired syn resolver's occurrence model.
//!
//! What the substrate buys over the syn walk it replaced:
//!
//! - **Canonical paths are definition paths** (edge targets join their
//!   `ItemFact` by stable key), so every re-export chain — `pub use` *and*
//!   `pub(crate) use` — resolves exactly; no Tier-2.5 blind spots.
//! - **Test exemption is structural**: the primary config is a plain `cargo
//!   check`, so `#[cfg(test)]` code is compiler-stripped and integration-test
//!   targets never compile; `references_from` additionally drops test-target
//!   fragments should the primary config carry them.
//! - **Macro expansions are visible**: a reference generated by a macro is a
//!   real compiled dependency edge and is judged like hand-written code,
//!   anchored at the invocation site (`Span::from_expansion` projection).
//!
//! The pass structure runs per module — single-name
//! imports claim `(canonical, rule)` first, then glob imports, then code
//! references dedup against both — so N call sites of a denied path still
//! collapse to one diagnostic anchored at the earliest surfaced form.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::path::PathBuf;

use wl_engine::fast::{CrateInfo, FastModel};
use wl_engine::semantic::{ResolvedRef, SemanticModel};

use crate::diagnostic::Diagnostic;

use super::{
    Anchor, ArchitectureConfig, CompiledRule, RefKind, build_diagnostic, canonical_prefixes,
    segments_to_glob_form,
};

pub(super) fn check(
    config: &ArchitectureConfig,
    fast: &FastModel,
    model: &SemanticModel,
) -> Vec<Diagnostic> {
    let compiled: Vec<CompiledRule> = config
        .rules
        .iter()
        .filter_map(CompiledRule::compile)
        .collect();
    if compiled.is_empty() {
        return Vec::new();
    }

    let mut diagnostics = Vec::new();
    for krate in fast.members() {
        // Rule `from` globs match *package* names (hyphenated), same as the
        // diagnostic's "from `<crate>`" display.
        let from_name = krate.name.as_str();
        if !compiled.iter().any(|r| r.matches_from(from_name)) {
            continue;
        }
        let crate_code = krate.code_name();

        // Group by enclosing module — the dedup grain the legacy walk had for
        // free — and order each module's references by use-site so the first
        // surfaced form of a violation is the one that anchors it.
        let refs = model.references_from(&crate_code);
        let mut by_module: BTreeMap<&[String], Vec<&ResolvedRef>> = BTreeMap::new();
        for r in &refs {
            by_module.entry(&r.module).or_default().push(r);
        }
        for (module, mut refs) in by_module {
            refs.sort_by(|a, b| span_order(a).cmp(&span_order(b)));
            let module_display = module.join("::");
            let mut reported: HashMap<String, HashSet<usize>> = HashMap::new();

            // Pass 1: single-name imports (`use a::B [as C]`) — judged on the
            // canonical item itself, claiming (canonical, rule).
            for r in refs.iter().filter(|r| r.import && !r.glob) {
                if is_own_crate_ref(r, &crate_code) {
                    continue;
                }
                for (rule_idx, rule) in compiled.iter().enumerate() {
                    if !rule.matches_from(from_name) || !rule.denies(&r.to_path) {
                        continue;
                    }
                    if rule.is_exception(&r.to_path) {
                        continue;
                    }
                    reported
                        .entry(segments_to_glob_form(&r.to_path))
                        .or_default()
                        .insert(rule_idx);
                    diagnostics.push(build_diagnostic(
                        rule,
                        from_name,
                        RefKind::Use(r.alias.as_deref()),
                        &r.to_path,
                        anchor(fast, krate, r),
                        &module_display,
                    ));
                }
            }
            // Pass 2: glob imports (`use m::*`) — tested as a representative
            // child of the target module, so `deny = ["m::**"]` (which targets
            // children, not the bare module) catches the wildcard import.
            for r in refs.iter().filter(|r| r.import && r.glob) {
                if is_own_crate_ref(r, &crate_code) {
                    continue;
                }
                let mut child = r.to_path.clone();
                child.push("*".to_string());
                for (rule_idx, rule) in compiled.iter().enumerate() {
                    if !rule.matches_from(from_name) || !rule.denies(&child) {
                        continue;
                    }
                    if rule.is_exception(&child) {
                        continue;
                    }
                    reported
                        .entry(segments_to_glob_form(&child))
                        .or_default()
                        .insert(rule_idx);
                    // Also claim the module itself: rustc (unlike syn) resolves
                    // code uses of glob-imported names, and each such reference
                    // carries the module as a prefix — the claim makes the
                    // code-ref pass fold them into this one glob diagnostic
                    // (the import line is the root cause; matches the legacy
                    // output where those uses were simply invisible).
                    reported
                        .entry(segments_to_glob_form(&r.to_path))
                        .or_default()
                        .insert(rule_idx);
                    diagnostics.push(build_diagnostic(
                        rule,
                        from_name,
                        RefKind::Glob,
                        &r.to_path,
                        anchor(fast, krate, r),
                        &module_display,
                    ));
                }
            }
            // Pass 3: code references. Each is tested against its canonical
            // and every prefix (`Type::method` matches a `Type` deny); the
            // shortest denied prefix is reported — unless an exception lies at
            // or below it, or an earlier pass already claimed any prefix.
            for r in refs.iter().filter(|r| !r.import) {
                if is_own_crate_ref(r, &crate_code) {
                    continue;
                }
                let prefixes = canonical_prefixes(&r.to_path);
                let prefix_keys: Vec<String> =
                    prefixes.iter().map(|p| segments_to_glob_form(p)).collect();
                for (rule_idx, rule) in compiled.iter().enumerate() {
                    if !rule.matches_from(from_name) {
                        continue;
                    }
                    let Some(denied_idx) = prefixes.iter().position(|p| rule.denies(p)) else {
                        continue;
                    };
                    if prefixes[denied_idx..].iter().any(|p| rule.is_exception(p)) {
                        continue;
                    }
                    if prefix_keys.iter().any(|k| {
                        reported
                            .get(k)
                            .is_some_and(|rules| rules.contains(&rule_idx))
                    }) {
                        continue;
                    }
                    reported
                        .entry(prefix_keys[denied_idx].clone())
                        .or_default()
                        .insert(rule_idx);
                    diagnostics.push(build_diagnostic(
                        rule,
                        from_name,
                        RefKind::Code,
                        &prefixes[denied_idx],
                        anchor(fast, krate, r),
                        &module_display,
                    ));
                }
            }
        }
    }

    diagnostics
}

/// Architecture rules govern *cross-crate* layering; a crate referencing its
/// own modules is never a violation. Both sides are code-form (underscored).
fn is_own_crate_ref(r: &ResolvedRef, crate_code: &str) -> bool {
    r.to_path.first().map(String::as_str) == Some(crate_code)
}

/// Use-site ordering key: (file, byte offset); the rare spanless edge sorts
/// first (it anchors at the crate, not a line — position is moot).
fn span_order(r: &ResolvedRef) -> Option<(&str, u32)> {
    r.span.as_ref().map(|s| (s.file.as_str(), s.lo))
}

/// Anchor at the use-site line. The IR's span files are workspace-relative
/// (rustc echoes the path cargo compiled from the workspace root) — exactly
/// the form the legacy backend's `crate_relative_path` produced, so pass
/// them through: the anchors, and everything keyed on them (suppression
/// matching, blessed fixture output), stay byte-identical across backends.
/// Spanless edges — dummy-span corners — fall back to the crate anchor.
fn anchor(fast: &FastModel, krate: &CrateInfo, r: &ResolvedRef) -> Anchor {
    match &r.span {
        Some(span) => Anchor::Line(PathBuf::from(&span.file), span.line),
        None => Anchor::Crate(fast.crate_relative_path(&krate.manifest_dir)),
    }
}
