//! Lint false-positive audit for the public-crate corpus (ROADMAP Phase 2).
//!
//! Runs the resolver-backed lints against real third-party crates (vendored as
//! git submodules under `corpus/`) and snapshots the diagnostics. A clean crate
//! produces an empty snapshot; any diagnostic is either a **real resolver false
//! positive** to fix, or — if it reflects a documented limitation — baked into
//! the committed snapshot with a `# known-FP:` note (the ROADMAP forcing function
//! as snapshot content). New, unexplained diagnostics fail the build.
//!
//! Scope: **`unused-deps` everywhere; `unused-pub` only on multi-member crates.**
//! On a standalone single-crate library every `pub` item has no cross-crate
//! referrer by construction, so `unused-pub` would flag the entire public API —
//! a closed-world lint assumption, not a resolver miss. It yields meaningful
//! signal only on a multi-member workspace (e.g. `thiserror`), where an internal
//! crate's `pub` items genuinely *are* referenced across crates, so a flag means
//! the resolver missed a reference. `unused-deps`, by contrast, means the
//! resolver failed to see a reference to a declared dependency — the false
//! positive we hunt on every crate. The per-crate config lives in
//! [`audit_config_for`].
//!
//! Each crate is copied to a tempdir (so the read-only submodule is never
//! mutated), a minimal audit config is written in, and the `workspace-lint`
//! binary runs there. `Workspace::load` uses `cargo metadata --no-deps`, so this
//! needs no network. **Skips cleanly** when the submodules aren't checked out.
//!
//! Bless: `WORKSPACE_LINT_BLESS=1 cargo test -p workspace-lint --test corpus_fp`.

use std::path::{Path, PathBuf};

use tempfile::TempDir;

mod common;
use common::{bless_enabled, copy_tree, normalize_stderr, workspace_lint};

/// Audit config copied into a corpus crate as `.workspace-lint.toml`. Sets a
/// blanket `default = "allow"` so the now-on-by-default structural lints
/// (centralized-deps, feature-drift, …) don't flag real third-party crates
/// that don't follow this workspace's conventions, then enables exactly the
/// resolver-backed lints under audit: `unused-deps` always, plus `unused-pub`
/// for multi-member workspaces (see the module docs). Levels stay `warn`: we
/// snapshot the diagnostics, we don't gate the exit code.
fn audit_config_for(entry: &CorpusEntry) -> String {
    let mut cfg = String::from(
        "# Phase 2 corpus false-positive audit (generated by tests/corpus_fp.rs).\n\
         [lints]\ndefault = \"allow\"\nunused-deps = \"warn\"\n",
    );
    if entry.multi_member {
        // On a multi-member workspace, `unused-pub` has real cross-crate signal.
        // `suppress-intra-crate` focuses the audit on the resolver-FP-prone
        // `Unused` class (an internal `pub` item the resolver thinks nothing
        // references), dropping the noisier "consider `pub(crate)`" style
        // suggestions that real crates trigger by using `pub` in private modules.
        //
        // `assume-all-public` keeps the audit about *resolver misses*, not
        // *publish policy*: the corpus crates are real published libraries that
        // don't bother writing `publish = true`, so the publish-aware default
        // would otherwise treat their whole public API as workspace-internal and
        // flag it (plus emit the `publish = true` hint) — noise unrelated to the
        // resolver behavior this audit gates.
        cfg.push_str(
            "unused-pub = \"warn\"\n\n[unused-pub]\nsuppress-intra-crate = true\nassume-all-public = true\n",
        );
    }
    cfg
}

struct CorpusEntry {
    name: &'static str,
    dir: &'static str,
    /// A cargo workspace with >1 member — enables the `unused-pub` audit.
    multi_member: bool,
}

const CORPUS: &[CorpusEntry] = &[
    CorpusEntry {
        name: "anyhow",
        dir: "anyhow",
        multi_member: false,
    },
    CorpusEntry {
        name: "bitflags",
        dir: "bitflags",
        multi_member: false,
    },
    CorpusEntry {
        name: "heck",
        dir: "heck",
        multi_member: false,
    },
    CorpusEntry {
        name: "itertools",
        dir: "itertools",
        multi_member: false,
    },
    // Deep cfg-gated arch-specific module tree (src/arch/…); single-crate, so
    // only `unused-deps` is audited. Stresses module-file resolution and
    // conditional `pub use` of `#[cfg(target_arch=…)]`-gated impls.
    CorpusEntry {
        name: "memchr",
        dir: "memchr",
        multi_member: false,
    },
    // thiserror lib + thiserror-impl proc-macro: a multi-member workspace, so
    // `unused-pub` is audited here (cross-crate referrers make it meaningful).
    CorpusEntry {
        name: "thiserror",
        dir: "thiserror",
        multi_member: true,
    },
];

#[test]
fn corpus_fp_audit() {
    let bless = bless_enabled();
    let corpus = corpus_root();
    let mut failures: Vec<String> = Vec::new();
    let mut ran = 0;

    for entry in CORPUS {
        let src = corpus.join(entry.dir);
        if !src.join("Cargo.toml").exists() {
            eprintln!(
                "corpus crate `{}` absent (no submodule?) — skipping",
                entry.name
            );
            continue;
        }
        ran += 1;
        if let Err(msg) = audit_one(entry, &src, bless) {
            failures.push(format!("[{}] {msg}", entry.name));
        }
    }

    if bless {
        eprintln!("Blessed {ran} corpus crate(s)");
        return;
    }
    if ran == 0 {
        eprintln!("no corpus crates present — skipping (run `git submodule update --init`)");
        return;
    }
    assert!(
        failures.is_empty(),
        "corpus FP-audit failures ({}/{} crates). A diagnostic is a real resolver \
         false positive to fix, or a documented known-FP to bless:\n{}",
        failures.len(),
        ran,
        failures.join("\n---\n")
    );
}

fn audit_one(entry: &CorpusEntry, src: &Path, bless: bool) -> Result<(), String> {
    let tmp = TempDir::new().map_err(|e| format!("tempdir: {e}"))?;
    copy_tree(src, tmp.path()).map_err(|e| format!("copy: {e}"))?;
    std::fs::write(
        tmp.path().join(".workspace-lint.toml"),
        audit_config_for(entry),
    )
    .map_err(|e| format!("write audit config: {e}"))?;

    let output = workspace_lint()
        .current_dir(tmp.path())
        .output()
        .map_err(|e| format!("spawn: {e}"))?;
    let stderr = normalize_stderr(&String::from_utf8_lossy(&output.stderr), tmp.path());

    let expected_path = expected_dir().join(format!("{}.stderr", entry.name));
    if bless {
        if let Some(parent) = expected_path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("mkdir: {e}"))?;
        }
        std::fs::write(&expected_path, &stderr).map_err(|e| format!("bless write: {e}"))?;
        return Ok(());
    }

    let expected = std::fs::read_to_string(&expected_path)
        .unwrap_or_default()
        .replace("\r\n", "\n");
    if expected.trim() != stderr.trim() {
        return Err(format!(
            "diagnostics changed (run WORKSPACE_LINT_BLESS=1 to update after triage).\n\
             expected:\n{expected}\n---\nactual:\n{stderr}"
        ));
    }
    Ok(())
}

fn corpus_root() -> PathBuf {
    // crates/workspace-lint/ -> repo root -> corpus/
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("workspace-lint crate has a repo root two levels up")
        .join("corpus")
}

fn expected_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus_fp")
}
