//! Lint false-positive audit for the public-crate corpus (ROADMAP Phase 2).
//!
//! Runs the resolver-backed lints against real third-party crates (vendored as
//! git submodules under `corpus/`) and snapshots the diagnostics. A clean crate
//! produces an empty snapshot; any diagnostic is either a **real resolver false
//! positive** to fix, or — if it reflects a documented limitation — baked into
//! the committed snapshot with a `# known-FP:` note (the ROADMAP forcing function
//! as snapshot content). New, unexplained diagnostics fail the build.
//!
//! Scope (first cut): **`unused-deps` only.** `unused-pub` is deliberately NOT
//! audited here — on a standalone single-crate library every `pub` item has no
//! cross-crate referrer by construction, so it would flag the entire public API.
//! That's a closed-world lint assumption, not a resolver miss; it yields a
//! meaningful signal only on a multi-crate corpus member (a follow-up). A
//! diagnostic from `unused-deps`, by contrast, means the resolver failed to see a
//! reference to a declared dependency — exactly the false positive we hunt.
//!
//! Each crate is copied to a tempdir (so the read-only submodule is never
//! mutated), a minimal audit config is written in, and the `workspace-lint`
//! binary runs there. `Workspace::load` uses `cargo metadata --no-deps`, so this
//! needs no network. **Skips cleanly** when the submodules aren't checked out.
//!
//! Bless: `WORKSPACE_LINT_BLESS=1 cargo test -p workspace-lint --test corpus_fp`.

use std::path::{Path, PathBuf};

use tempfile::TempDir;

mod common;
use common::{bless_enabled, copy_tree, normalize_stderr, workspace_lint};

/// Audit config copied into each corpus crate as `.workspace-lint.toml`. Enables
/// only the lint whose diagnostics signal a resolver miss on a standalone crate
/// (see the module docs for why `unused-pub` is excluded). Levels stay default
/// (`warn`): we snapshot the diagnostics, we don't gate the exit code.
const AUDIT_CONFIG: &str = "\
# Phase 2 corpus false-positive audit (generated by tests/corpus_fp.rs).\n\
[unused-deps]\n";

struct CorpusEntry {
    name: &'static str,
    dir: &'static str,
}

const CORPUS: &[CorpusEntry] = &[
    CorpusEntry {
        name: "anyhow",
        dir: "anyhow",
    },
    CorpusEntry {
        name: "bitflags",
        dir: "bitflags",
    },
    CorpusEntry {
        name: "heck",
        dir: "heck",
    },
    CorpusEntry {
        name: "itertools",
        dir: "itertools",
    },
];

#[test]
fn corpus_fp_audit() {
    let bless = bless_enabled();
    let corpus = corpus_root();
    let mut failures: Vec<String> = Vec::new();
    let mut ran = 0;

    for entry in CORPUS {
        let src = corpus.join(entry.dir);
        if !src.join("Cargo.toml").exists() {
            eprintln!(
                "corpus crate `{}` absent (no submodule?) — skipping",
                entry.name
            );
            continue;
        }
        ran += 1;
        if let Err(msg) = audit_one(entry, &src, bless) {
            failures.push(format!("[{}] {msg}", entry.name));
        }
    }

    if bless {
        eprintln!("Blessed {ran} corpus crate(s)");
        return;
    }
    if ran == 0 {
        eprintln!("no corpus crates present — skipping (run `git submodule update --init`)");
        return;
    }
    assert!(
        failures.is_empty(),
        "corpus FP-audit failures ({}/{} crates). A diagnostic is a real resolver \
         false positive to fix, or a documented known-FP to bless:\n{}",
        failures.len(),
        ran,
        failures.join("\n---\n")
    );
}

fn audit_one(entry: &CorpusEntry, src: &Path, bless: bool) -> Result<(), String> {
    let tmp = TempDir::new().map_err(|e| format!("tempdir: {e}"))?;
    copy_tree(src, tmp.path()).map_err(|e| format!("copy: {e}"))?;
    std::fs::write(tmp.path().join(".workspace-lint.toml"), AUDIT_CONFIG)
        .map_err(|e| format!("write audit config: {e}"))?;

    let output = workspace_lint()
        .current_dir(tmp.path())
        .output()
        .map_err(|e| format!("spawn: {e}"))?;
    let stderr = normalize_stderr(&String::from_utf8_lossy(&output.stderr), tmp.path());

    let expected_path = expected_dir().join(format!("{}.stderr", entry.name));
    if bless {
        if let Some(parent) = expected_path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("mkdir: {e}"))?;
        }
        std::fs::write(&expected_path, &stderr).map_err(|e| format!("bless write: {e}"))?;
        return Ok(());
    }

    let expected = std::fs::read_to_string(&expected_path)
        .unwrap_or_default()
        .replace("\r\n", "\n");
    if expected.trim() != stderr.trim() {
        return Err(format!(
            "diagnostics changed (run WORKSPACE_LINT_BLESS=1 to update after triage).\n\
             expected:\n{expected}\n---\nactual:\n{stderr}"
        ));
    }
    Ok(())
}

fn corpus_root() -> PathBuf {
    // crates/workspace-lint/ -> repo root -> corpus/
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("workspace-lint crate has a repo root two levels up")
        .join("corpus")
}

fn expected_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus_fp")
}
